files:
  - source: /**/*.properties
    ignore:
      - /**/*core.properties
      - /**/jetty-logging.properties
      - /**/*_*.properties
    translation: /**/%file_name%_%two_letters_code%.properties
