files:
  - 
    source: /**/*.properties
    ignore:
      - /**/*core.properties
      - /**/jetty-logging.properties
      - /**/*_*.properties
    translation: /**/%original_file_name%_%two_letters_code%.properties
    languages_mapping:
      two_letters_code:
        en-CA: en_CA
  - 
    source: /**/*Translations.xml
    translation: /**/%file_name%.%two_letters_code%.xml
    translatable_elements:
      - /xwikidoc/content
